"""autogenerated by genmsg_py from X10.msg. Do not edit."""
import roslib.message
import struct


class X10(roslib.message.Message):
  _md5sum = "412ad5f78068f9ac88fb2866fbc7c142"
  _type = "vp_x10_voice/X10"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 command1
int16 command2
int16 repeatTime



"""
  __slots__ = ['command1','command2','repeatTime']
  _slot_types = ['int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       command1,command2,repeatTime
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(X10, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.command1 is None:
        self.command1 = 0
      if self.command2 is None:
        self.command2 = 0
      if self.repeatTime is None:
        self.repeatTime = 0
    else:
      self.command1 = 0
      self.command2 = 0
      self.repeatTime = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_3h.pack(_x.command1, _x.command2, _x.repeatTime))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.command1, _x.command2, _x.repeatTime,) = _struct_3h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_3h.pack(_x.command1, _x.command2, _x.repeatTime))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.command1, _x.command2, _x.repeatTime,) = _struct_3h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_3h = struct.Struct("<3h")
